flowchart LR
  subgraph s6466["형법"]
    k0["감경"]
    k1["경악"]
    k2["당황"]
    k3["면제"]
    k4["방위행위"]
    k5["법익"]
    k6["야간기타불안"]
    k7["정황"]
    k8["흥분"]
  end
  subgraph s1696["민법"]
    k9["급박"]
    k10["상당"]
    k11["정당방위"]
    k12["행위"]
  end
  subgraph s1099["대한민국헌법"]
    k13["방위"]
  end
  subgraph s4654["상법"]
    k14["부당"]
    k15["초과"]
  end
  subgraph s3965["형사소송법"]
    k16["불안"]
    k17["상태하"]
    k18["이유"]
    k19["현재"]
  end
  subgraph s5026["근로기준법"]
    k20["야간"]
  end
  subgraph s4931["저작권법"]
    k21["침해"]
  end
  k21 ==>|설명함| k12
  k11 ==>|설명함| k13
  k11 ==>|설명함| k12
  k3 ==>|설명함| k15
  k11 ==>|설명함| k0
  k11 ==>|설명함| k1
  k12 ==>|설명함| k15
  k3 ==>|설명함| k12
  k14 ==>|설명함| k15
  k10 -.->|같은조문| k18
  k0 -.->|같은조문| k3
  k10 -.->|같은조문| k15
  k14 -.->|같은조문| k18
  k3 -.->|같은조문| k10
  k14 -.->|같은조문| k21
  k14 -.->|같은조문| k10
  k0 -.->|같은조문| k21
  k5 -.->|같은조문| k18
  k5 -.->|같은조문| k19
  k18 -.->|같은조문| k19
  k13 -.->|같은조문| k19
  k0 -.->|같은조문| k7
  k1 -.->|같은조문| k2
  k1 -.->|같은조문| k13
  k1 -.->|같은조문| k4
  k2 -.->|같은조문| k13
  k2 -.->|같은조문| k4
  k2 -.->|같은조문| k5
  k4 -.->|같은조문| k5
  k4 -.->|같은조문| k16
  k16 -.->|같은조문| k17
  k16 -.->|같은조문| k20
  k16 -.->|같은조문| k6
  k17 -.->|같은조문| k20
  k17 -.->|같은조문| k6
  k17 -.->|같은조문| k7
  k20 -.->|같은조문| k6
  k20 -.->|같은조문| k7
  k6 -.->|같은조문| k7
  k21 -.->|같은조문| k19
  classDef 중심 fill:#1d4ed8,stroke:#1e3a8a,color:#fff
  class k11 중심
