flowchart BT
  c0["과도"]
  c1(["흉기"])
  c2(["칼"])
  c3["식칼"]
  c4["회칼"]
  c5["잭나이프"]
  c6["각목"]
  c7["쇠파이프"]
  c8["망치"]
  c9["벽돌"]
  c10["날붙이"]
  c0 ---|상위| c1
  c0 ---|상위| c2
  c3 ---|상위| c1
  c3 ---|상위| c2
  c4 ---|상위| c1
  c4 ---|상위| c2
  c5 ---|상위| c1
  c5 ---|상위| c2
  c6 ---|상위| c1
  c7 ---|상위| c1
  c8 ---|상위| c1
  c9 ---|상위| c1
  c10 ---|상위| c1
  c2 ---|상위| c1
  classDef 상위 fill:#0E7490,stroke:#134E4A,color:#fff
  class c2,c1 상위
